=== jwierzbi/chinese/xml/schemas/characters.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="characters">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="character" minOccurs="1" maxOccurs="100">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="symbol" type="xs:string"/>
              <xs:element name="pinyin" type="xs:string"/>
              <xs:element name="meaning" type="xs:string"/>
              <xs:element name="note" type="xs:string"/>
              <xs:element name="radical" type="xs:string"/>
              <xs:element name="components">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="component" type="xs:string"
                                minOccurs="0" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jwierzbi/chinese/xml/0101_0200.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="schemas/characters.xsd">
<!-- 101 -->
  <character>
    <symbol>地</symbol>
    <pinyin>de</pinyin>
    <meaning>-ly structural particle</meaning>
    <note/>
    <radical>土</radical>
    <components>
      <component>土</component>
      <component>也</component>
    </components>
  </character>
  <character>
    <symbol>再</symbol>
    <pinyin>zài</pinyin>
    <meaning>again; then</meaning>
    <note/>
    <radical>冂</radical>
    <components>
      <component>一</component>
      <component>冉</component>
    </components>
  </character>
  <character>
    <symbol>因</symbol>
    <pinyin>yīn</pinyin>
    <meaning>reason</meaning>
    <note/>
    <radical>囗</radical>
    <components>
      <component>囗</component>
      <component>大</component>
    </components>
  </character>
  <character>
    <symbol>呢</symbol>
    <pinyin>ne</pinyin>
    <meaning>how about…?; continuing particle</meaning>
    <note/>
    <radical>口</radical>
    <components>
      <component>口</component>
      <component>尼</component>
    </components>
  </character>
  <character>
    <symbol>女</symbol>
    <pinyin>nǚ</pinyin>
    <meaning>female</meaning>
    <note/>
    <radical>女</radical>
    <components>
      <component>丆</component>
    </components>
  </character>
  <character>
    <symbol>告</symbol>
    <pinyin>gào</pinyin>
    <meaning>to tell</meaning>
    <note/>
    <radical>口</radical>
    <components>
      <component>口</component>
    </components>
  </character>
  <character>
    <symbol>最</symbol>
    <pinyin>zuì</pinyin>
    <meaning>most; -est</meaning>
    <note/>
    <radical>冂</radical>
    <components>
      <component>日</component>
      <component>取</component>
    </components>
  </character>
  <character>
    <symbol>手</symbol>
    <pinyin>shǒu</pinyin>
    <meaning>hand</meaning>
    <note/>
    <radical>手</radical>
    <components>
      <component>丿</component>
      <component>扌</component>
    </components>
  </character>
  <character>
    <symbol>前</symbol>
    <pinyin>qián</pinyin>
    <meaning>front</meaning>
    <note/>
    <radical>刀</radical>
    <components>
      <component>䒑</component>
      <component>刖</component>
    </components>
  </character>
  <character>
    <symbol>找</symbol>
    <pinyin>zhǎo</pinyin>
    <meaning>to look for</meaning>
    <note>Hand 扌 searching for halberd 戈.</note>
    <radical>手</radical>
    <components>
      <component>扌</component>
      <component>戈</component>
    </components>
  </character>
<!-- 111 -->
  <character>
    <symbol>行</symbol>
    <pinyin>xíng</pinyin>
    <meaning>to travel; OK!</meaning>
    <note/>
    <radical>行</radical>
    <components>
      <component>彳</component>
      <component>亍</component>
    </components>
  </character>
  <character>
    <symbol>快</symbol>
    <pinyin>kuài</pinyin>
    <meaning>rapid; almost</meaning>
    <note/>
    <radical>心</radical>
    <components>
      <component>忄</component>
      <component>夬</component>
    </components>
  </character>
  <character>
    <symbol>而</symbol>
    <pinyin>ér</pinyin>
    <meaning>and; as well as</meaning>
    <note/>
    <radical>而</radical>
    <components>
      <component>丆</component>
    </components>
  </character>
  <character>
    <symbol>死</symbol>
    <pinyin>sǐ</pinyin>
    <meaning>to die</meaning>
    <note/>
    <radical>歹</radical>
    <components>
      <component>歹</component>
      <component>匕</component>
    </components>
  </character>
  <character>
    <symbol>先</symbol>
    <pinyin>xiān</pinyin>
    <meaning>first; former</meaning>
    <note/>
    <radical>儿</radical>
    <components>
      <component>儿</component>
    </components>
  </character>
  <character>
    <symbol>像</symbol>
    <pinyin>xiàng</pinyin>
    <meaning>to be like; image</meaning>
    <note/>
    <radical>人</radical>
    <components>
      <component>亻</component>
      <component>象</component>
    </components>
  </character>
  <character>
    <symbol>等</symbol>
    <pinyin>děng</pinyin>
    <meaning>rank; to wait for </meaning>
    <note/>
    <radical>竹</radical>
    <components>
      <component>寺</component>
    </components>
  </character>
  <character>
    <symbol>被</symbol>
    <pinyin>bèi</pinyin>
    <meaning>passive particle</meaning>
    <note/>
    <radical>衣</radical>
    <components>
      <component>衤</component>
      <component>皮</component>
    </components>
  </character>
  <character>
    <symbol>從</symbol>
    <pinyin>cóng</pinyin>
    <meaning>from; to follow</meaning>
    <note>One man 人 follows another 人 on foot 彳.</note>
    <radical>彳</radical>
    <components>
      <component>彳</component>
      <component>从</component>
      <component>龰</component>
    </components>
  </character>
  <character>
    <symbol>明</symbol>
    <pinyin>míng</pinyin>
    <meaning>bright</meaning>
    <note>Things that are bright: the sun 日 and the moon 月.</note>
    <radical>日</radical>
    <components>
      <component>日</component>
      <component>月</component>
    </components>
  </character>
<!-- 121 -->
  <character>
    <symbol>中</symbol>
    <pinyin>zhōng</pinyin>
    <meaning>middle</meaning>
    <note/>
    <radical>丨</radical>
    <components>
      <component>口</component>
      <component>丨</component>
    </components>
  </character>
  <character>
    <symbol>哦</symbol>
    <pinyin>ó</pinyin>
    <meaning>oh</meaning>
    <note/>
    <radical>口</radical>
    <components>
      <component>口</component>
      <component>我</component>
    </components>
  </character>
  <character>
    <symbol>情</symbol>
    <pinyin>qíng</pinyin>
    <meaning>emotion</meaning>
    <note/>
    <radical>心</radical>
    <components>
      <component>忄</component>
      <component>青</component>
    </components>
  </character>
  <character>
    <symbol>作</symbol>
    <pinyin>zuò</pinyin>
    <meaning>to do</meaning>
    <note/>
    <radical>人</radical>
    <components>
      <component>亻</component>
      <component>乍</component>
    </components>
  </character>
  <character>
    <symbol>跟</symbol>
    <pinyin>gēn</pinyin>
    <meaning>with; to follow</meaning>
    <note/>
    <radical>足</radical>
    <components>
      <component>足</component>
      <component>艮</component>
    </components>
  </character>
  <character>
    <symbol>面</symbol>
    <pinyin>miàn</pinyin>
    <meaning>face; aspect</meaning>
    <note/>
    <radical>面</radical>
    <components>
      <component>丆</component>
      <component>囬</component>
    </components>
  </character>
  <character>
    <symbol>愬</symbol>
    <pinyin>sù</pinyin>
    <meaning>to tell; to complain</meaning>
    <note/>
    <radical>心</radical>
    <components>
      <component>朔</component>
      <component>心</component>
    </components>
  </character>
  <character>
    <symbol>愛</symbol>
    <pinyin>ài</pinyin>
    <meaning>to love</meaning>
    <note/>
    <radical>心</radical>
    <components>
      <component>夂</component>
      <component>冖</component>
      <component>心</component>
    </components>
  </character>
  <character>
    <symbol>已</symbol>
    <pinyin>yǐ</pinyin>
    <meaning>already</meaning>
    <note/>
    <radical>己</radical>
    <components>
      <component>己</component>
    </components>
  </character>
  <character>
    <symbol>之</symbol>
    <pinyin>zhī</pinyin>
    <meaning>possessive particle</meaning>
    <note/>
    <radical>丿</radical>
    <components/>
  </character>
<!-- 131 -->
<!-- 141 -->
<!-- 151 -->
<!-- 161 -->
<!-- 171 -->
<!-- 181 -->
<!-- 191 -->
</characters>

=== jwierzbi/chinese/xml/0301_0400.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="schemas/characters.xsd">
<!-- 301 -->
  <character>
    <symbol>嗨</symbol>
    <pinyin>hāi</pinyin>
    <meaning>an exclamation</meaning>
    <note/>
    <radical>口</radical>
    <components>
      <component>口</component>
      <component>海</component>
    </components>
  </character>
  <character>
    <symbol>房</symbol>
    <pinyin>fáng</pinyin>
    <meaning>house; room</meaning>
    <note/>
    <radical>戶</radical>
    <components>
      <component>戶</component>
      <component>方</component>
    </components>
  </character>
  <character>
    <symbol>命</symbol>
    <pinyin>mìng</pinyin>
    <meaning>life; fate</meaning>
    <note/>
    <radical>口</radical>
    <components>
      <component>亼</component>
      <component>叩</component>
    </components>
  </character>
  <character>
    <symbol>且</symbol>
    <pinyin>qiě</pinyin>
    <meaning>moreover; both</meaning>
    <note/>
    <radical>一</radical>
    <components>
      <component>月</component>
      <component>一</component>
    </components>
  </character>
  <character>
    <symbol>向</symbol>
    <pinyin>xiàng</pinyin>
    <meaning>towards; direction</meaning>
    <note/>
    <radical>口</radical>
    <components>
      <component>口</component>
      <component>丶</component>
    </components>
  </character>
  <character>
    <symbol>興</symbol>
    <!-- <symbol>兴</symbol> -->
    <pinyin>xīng</pinyin>
    <meaning>to rise; to flourish</meaning>
    <note/>
    <radical>臼</radical>
    <components>
      <component>臼</component>
      <component>同</component>
      <component>一</component>
      <component>八</component>
    </components>
  </character>
  <character>
    <symbol>球</symbol>
    <pinyin>qiú</pinyin>
    <meaning>ball; sphere</meaning>
    <note/>
    <radical>玉</radical>
    <components>
      <component>王</component>
      <component>求</component>
    </components>
  </character>
  <character>
    <symbol>服</symbol>
    <pinyin>fú</pinyin>
    <meaning>clothes; to serve</meaning>
    <note/>
    <radical>月</radical>
    <components>
      <component>月</component>
    </components>
  </character>
  <character>
    <symbol>入</symbol>
    <pinyin>rù</pinyin>
    <meaning>to enter</meaning>
    <note/>
    <radical>入</radical>
    <components/>
  </character>
  <character>
    <symbol>照</symbol>
    <pinyin>zhào</pinyin>
    <meaning>according to; to shine; photo</meaning>
    <note/>
    <radical>火</radical>
    <components>
      <component>昭</component>
      <component>灬</component>
    </components>
  </character>
<!-- 311 -->
  <character>
    <symbol>提</symbol>
    <pinyin>tí</pinyin>
    <meaning>to lift</meaning>
    <note/>
    <radical>手</radical>
    <components>
      <component>扌</component>
      <component>是</component>
    </components>
  </character>
  <character>
    <symbol>掉</symbol>
    <pinyin>diào</pinyin>
    <meaning>to fall; to lose</meaning>
    <note/>
    <radical>手</radical>
    <components>
      <component>扌</component>
      <component>卓</component>
    </components>
  </character>
  <character>
    <symbol>夫</symbol>
    <pinyin>fū</pinyin>
    <meaning>husband</meaning>
    <note/>
    <radical>大</radical>
    <components>
      <component>人</component>
      <component>二</component>
    </components>
  </character>
  <character>
    <symbol>路</symbol>
    <pinyin>lù</pinyin>
    <meaning>road</meaning>
    <note/>
    <radical>足</radical>
    <components>
      <component>各</component>
    </components>
  </character>
  <character>
    <symbol>演</symbol>
    <pinyin>yǎn</pinyin>
    <meaning>to act; to develop</meaning>
    <note/>
    <radical>水</radical>
    <components>
      <component>氵</component>
      <component>寅</component>
    </components>
  </character>
  <character>
    <symbol>夠</symbol>
    <!-- <symbol>够</symbol> -->
    <pinyin>gòu</pinyin>
    <meaning>to be enough</meaning>
    <note/>
    <radical>夕</radical>
    <components>
      <component>多</component>
      <component>句</component>
    </components>
  </character>
  <character>
    <symbol>日</symbol>
    <pinyin>rì</pinyin>
    <meaning>sun; day</meaning>
    <note>Picture of the sun, which rises every day over the horison.</note>
    <radical>日</radical>
    <components>
      <component>口</component>
      <component>一</component>
    </components>
  </character>
  <character>
    <symbol>案</symbol>
    <pinyin>àn</pinyin>
    <meaning>legal case; record</meaning>
    <note/>
    <radical>木</radical>
    <components>
      <component>安</component>
      <component>木</component>
    </components>
  </character>
  <character>
    <symbol>舞</symbol>
    <pinyin>wǔ</pinyin>
    <meaning>to dance</meaning>
    <note/>
    <radical>舛</radical>
    <components>
      <component>舛</component>
      <component>卌</component>
      <component>一</component>
    </components>
  </character>
  <character>
    <symbol>決</symbol>
    <!-- <symbol>决</symbol> -->
    <pinyin>jué</pinyin>
    <meaning>to decide</meaning>
    <note/>
    <radical>水</radical>
    <components>
      <component>氵</component>
      <component>夬</component>
    </components>
  </character>
</characters>
